### ISSUE TITLE
+[SBDMain addExtension:version:]: unrecognized selector sent to class 0x1062a0128

### ISSUE THREAD

**Issue by jonchui** [sendbird/sendbird-uikit-ios#11]
I can run the sample app fine, but when i try to add this to my app (which was using SBDMain before), i get this error:

```
+[SBDMain addExtension:version:]: unrecognized selector sent to class 0x1062a0128
```

When calling 
```
SBUMain.initialize(applicationId:applicationId)
```

We call this in `applicationDidFinishLaunching` in a static function. 

the EXACT same appID and pod versions work for the sample app - leading me to think there's something in our code that is changing SBDMain before this call to SBUMain.intialize?

![image](https://user-images.githubusercontent.com/204868/82087106-b1380000-96ac-11ea-9082-17e9df498f2d.png)

**Comment by jonchui** [comment]
Totally lied - the difference was your sample was using  `SendbirdSDK` @ 3.0.179 and I had 3.0.175


`Installing SendBirdSDK 3.0.179 (was 3.0.175 and source changed to `https://cdn.cocoapods.org/` from `trunk`)`

PS - you should probably make SendbirdSDK >= 

https://github.com/sendbird/sendbird-uikit-ios/blob/master/SendBirdUIKit.podspec

`s.dependency "SendBirdSDK", "~>3.0.179"`

**Comment by jonchui** [comment]
Made the change here: https://github.com/jonchui/sendbird-uikit-ios/blob/master/SendBirdUIKit.podspec

But couldn't find out how to make a PR for your repo - maybe i need write access?

**Comment by tezpark** [comment]
Hello @jonchui 
We do not yet support external PR. But, we will consider external PR support in a positive direction.

And, Thanks to your issue report, we were able to respond quickly to the problem!
Thanks for reporting 👍
