### ISSUE TITLE
Any sample code for how to use this uikit?

### ISSUE THREAD

**Issue by Chren** [sendbird/sendbird-uikit-ios#2]
It seems there's only frameworks in this repository. 
Any sample code for how to use sendbird uikit?
Thanks.

**Comment by tezpark** [comment]
For a sample of uikit, please check the repository below.
[SendBird-iOS Sample](https://github.com/sendbird/SendBird-iOS)

And you can find more information through the documentation page.
[SendBird UIKit Docs](https://docs.sendbird.com/ios/ui_kit_getting_started#2_uikit_for_ios)

Thanks for reporting the issue.
