### ISSUE TITLE
Customising navigation bar button items in SBUChannelListViewController 

### ISSUE THREAD

**Issue by minon250** [sendbird/sendbird-uikit-ios#4]
I want to use the default behaviour of the SBUChannelListViewController however I want to get rid of the navigation bar button items which include a back button and the create channel button. How can I get this done?

**Comment by tezpark** [comment]
Hello, @minon250 
We don't support navigation button customization yet.
However, we'll reflect the requested features quickly in the next update!

Thanks to @minon250 for reporting the issue.

**Comment by minon250** [comment]
Hello, @tezpark  appreciate your prompt response and great work with the SBD UIKit. It has been really great. We are a fast-growing startup and we've really enjoyed using SendBird. So keep up the good work. 

Feature enhancement requests: 
1. Message grouping when messages are sent by the same user back to back 
2. Ability to add more options in the SBUChannelSettingsViewController
3. Request confirmation when deleting a channel

Also, I would like to know how to show the loading indicator when channels are being loaded. 

Thank You

**Comment by tezpark** [comment]
Hi, @minon250 
Thanks for your active feedback! 👍 

Please check answers:

1. Grouping messages from the same users is under consideration. If you want to try it quickly, checking docs's customize section.
[Channel's Customize the class](https://docs.sendbird.com/ios/ui_kit_key_functions#3_chat_in_a_channel_4_customize_the_class)
2. See also Channel [Settings's Customize the class](https://docs.sendbird.com/ios/ui_kit_key_functions#3_configure_channel_settings_4_customize_the_class) section for the ability to add more options.
3. Perhaps the channel deletion you talked about is leaving the channel. To handle when leaving a channel, override the `open func channel (_ sender: SBDGroupChannel, userDidLeave user: SBDUser)` function of `SBUChannelListViewController`.

All three requests can be helpful by referring to the section related to customization in docs.

And, the working to display the loading indicator when a channel is loaded will be updated soon.

Thank you :)

**Comment by PabloLerma** [comment]
Hey @minon250 !

I think it is possible to remove the navigation bar button items as you requested subclassing `SBUChannelListViewController` and removing the bar buttons like this:
```
override func viewDidLoad() {
		super.viewDidLoad()

		navigationItem.leftBarButtonItem = nil
		navigationItem.rightBarButtonItem = nil
	}
```

**Comment by tezpark** [comment]
Thanks, @PabloLerma !
Your example is correct. 
You can use the nil value to remove the bar button, and to customize it, you can add your own BarButtonItem.
