### ISSUE TITLE
Loading Indicator

### ISSUE THREAD

**Issue by minon250** [sendbird/sendbird-uikit-ios#5]
I can see that the SBUChatListVC and SBUChannelVC have the ability to show the loading indicator. However, the documentation is not clear as to how it can be handled. Is it possible to show the loading indicator when channels or messages are being loaded?

**Comment by tezpark** [comment]
The loading indicator is currently not controlled externally.
We will modify the channel list to be exposed the first time it is loaded. but not exposed during pagination.

Feel free to give us additional comments.
