### ISSUE TITLE
Create new channel opens another channel list instead of going back to the existing one

### ISSUE THREAD

**Issue by RomanTysiachnik** [sendbird/sendbird-uikit-ios#7]
## Description
We've mentioned a very poor UX when we create a new channel. Create action presents another channel list and pushes to the created channel instead of returning back to that list.

## Preconditions
- RootController - `UITabBarViewController`
- `SBUChannelListViewController` is a child of another composite view controller 
- Composite view controller wrapped in navigation controller

## How to reproduce
1. Press on a create new channel button on the Channels list
2. Select one or few users and press `Create`

**Expected result:** 
Create channel screen pops to channel list screen and then a newly created chat is pushed

**Achieved result**
Channel list screen is presented above the create channel screen and then a newly created chat is pushed. If you close presented screen, you're getting back to the channel creation.

## Issue
The issue is probably connected with the logic that decides if it should present channel list, or if it should go back to if it is a root view controller. But the thing is, that the channel list may be inside of many other view controllers that wrap it, so it doesn't work properly.

## Environment
- Xcode 11.4
- SendBirdUIKit 1.0.3

**Comment by intoxicated** [comment]
Hey @RomanTysiachnik I think this is bug and will look into it. I think a new channel should just be pushed and the list has to be displayed when backing from the channel. I will discuss with our team with this matter

**Comment by tezpark** [comment]
Hello @RomanTysiachnik 

Thanks to your reporting, we were able to correct our problems!
We have released the issue you reported in the 1.0.5 version.

Thanks for reporting 👍

**Comment by RomanTysiachnik** [comment]
@tezpark Hi! Cool, thanks! 👍
