### ISSUE TITLE
Carthage install requires base SDK as well

### ISSUE THREAD

**Issue by beltex** [sendbird/sendbird-uikit-ios#9]
Hello SendBird! The UIKit SDK has been smooth so far, ran into just one minor hitch. 

Seems that if the base SendBird SDK (`github "sendbird/sendbird-ios-framework"`) is not defined in one's `Cartfile`, then you get a compiler error on import of `SendBirdUIKit`, in which the compiler complains about a missing module (`SendBirdSDK`).

So either the docs need to be updated to mention this or the UIKit dependancy should include it (the CocoaPods install seems to do this already).

**Comment by tezpark** [comment]
Hello, @beltex 
Thanks to your reporting! 
We'll be working on improvements to Carthage and CocoaPod to reflect our opinions!
I'll let you know when it's done.

**Comment by beltex** [comment]
np, thanks!

**Comment by tezpark** [comment]
Hi, @beltex .
We have released the issue you reported in the 1.0.6 version.
And I added the relevant content to the README.
Thanks for reporting 👍
